### ISSUE TITLE
Exclude Files from Deploy

### ISSUE THREAD

**Issue by NathanGrenier** [sonic-howl/frc2024#18]
### 🐛 Issue Summary:

Currently, there doesn't seem to be a way to exclude files from the deploy process. This is an issue because the project contains a static folder that hosts images for the readme on GitHub.

### 📜 Description:

The deploy process is described [here](https://robotpy.readthedocs.io/en/stable/dev/deploy.html#deploy-process-details).

### ✅ Expected Behavior:

Should be a way to exclude files from deploy process.

### ❌ Actual Behavior:

There isn't a way in python.

### 💡 Possible Solutions

Since the project is copied to the RIO depending on where `robot.py` file is located in the project structure, use a subdirectories that includes the `robot.py` file to specify what should get copied.

### Additional Information:

**📷 Screenshots / Code Snippets**

![image](https://github.com/sonic-howl/frc2024/assets/56941028/c6dfbf99-ded2-47cb-be6d-cf3c54dd6c4a)

**Comment by NeilTheFisher** [comment]
We could make a pr to [robotpy-installer](https://github.com/robotpy/robotpy-installer) to add a `--ignore` flag to ignore files, or we could move the robot.py file into it's own src directory so it would be the only directory to be deployed to the RoboRIO.

Sidenote: if we want to use venv, that pr would make it work. Otherwise, using the flags `--system-site-packages` and `--symlinks` from the [venv options](https://docs.python.org/3/library/venv.html) could work, but it would still copy the venv to the RIO

**Comment by NathanGrenier** [comment]
>(...) or we could move the robot.py file into it's own src directory so it would be the only directory to be deployed to the RoboRIO.

Seems like the simplest solution and the one we should probably try first.

There might also be a way to exclude files in the `pyproject.toml` file, but the documentation for that is lacking.
